name: Run Test

on:
    push:
      branches:
            - 'main'
    pull_request:
         branches:
            - 'main'

jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            persist-credentials: false
            ref: ${{ github.event.inputs.checkoutRef }}
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependecies
          run : npm ci
        - name: Run test
          run : npm test 