name: Run Test

on:
    push:
      branches:
            - 'main'
    pull_request:
         branches:
            - 'main'

jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: action/checkout@v2
        - name: Setup Node
          uses: action/setup-node@v2
          with:
            node-version: 18.16.1
        - name: Install Dependecies
          run : npm ci
        - name: Run test
          run : npm test 